name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      env:
        working-directory: ./advent_of_code
      run: cargo build --verbose
    - name: Run tests
      env:
        working-directory: ./advent_of_code
      run: cargo test --verbose
